name: Update HID Database

on:
  push:
    paths:
      - "maps/**/*.json"
      - "maps/*.json"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate database
        run: python tools/generate_database.py

      - name: Commit changes
        run: |
          git add database.json

          if git diff --cached --quiet --exit-code; then
            echo "database.json already up to date."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit -m "Auto-update database.json"
          git push